services:
  - type: web
    name: skylarbox-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      # Add your DB or other env variables here
      # - key: DATABASE_URL
      #   value: mysql://user:pass@host:port/db
